version: '3.4'

services:
  processoseletivongcash:
    image: processoseletivongcash
    networks:
      - host
    build: .
    command: npm run dev
    environment:
      NODE_ENV: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app

networks:
  host:
    name: host
    external: true
    driver: host.docker.internal